// Source: RVL SDK
#include <kamek.h>

#ifdef __cplusplus
extern "C" {
#endif

enum OSError {
    OS_ERROR_SYSTEM_RESET,
    OS_ERROR_MACHINE_CHECK,
    OS_ERROR_DSI,
    OS_ERROR_ISI,
    OS_ERROR_EXTERNAL_INTERRUPT,
    OS_ERROR_ALIGNMENT,
    OS_ERROR_PROGRAM,
    OS_ERROR_FP_UNAVAILABLE,
    OS_ERROR_DECREMENTER,
    OS_ERROR_SYSTEM_CALL,
    OS_ERROR_TRACE,
    OS_ERROR_PERFORMANCE_MONITOR,
    OS_ERROR_BREAKPOINT,
    OS_ERROR_SYSTEM_INTERRUPT,
    OS_ERROR_THERMAL_INTERRUPT,
    OS_ERROR_PROTECTION,
    OS_ERROR_FPE,
};

#ifdef __cplusplus
}
#endif
